name: Deploy

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "blazorazuretest55"
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure authentication
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker Build & Push
        run: |
          docker build . -t ${{ env.CONTAINER_REGISTRY }}/myapp:${{ github.sha }}
          docker push ${{ env.CONTAINER_REGISTRY }}/myapp:${{ github.sha }}

      - name: "Deploy to Azure Web App for Container"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.CONTAINER_REGISTRY }}/myapp:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout

      # - name: Docker build and push
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'myapp'
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     images: 'mycontainer.azurecr.io/myapp:${{ github.sha }}'
