name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build and push
        uses: azure/docker-login@v2
        with:
          login-server: blazorazuretest.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t blazorazuretest.azurecr.io/myapp:${{ github.sha }}
          docker push blazorazuretest.azurecr.io/myapp:${{ github.sha }}

      # - name: Docker build and push
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'myapp'
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     images: 'mycontainer.azurecr.io/myapp:${{ github.sha }}'
